package com.cfs.CREDENCE_20.service;
import com.cfs.CREDENCE_20.dto.AiRootResponse;
import com.cfs.CREDENCE_20.dto.ClinicalReportResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

// converts Ai response to spring Object
@Service
public class AiGenerationService {

    // Groq hosts open models (Llama, etc.) for free behind an OpenAI-compatible
    // chat completions API, which is why AiRootResponse (choices -> message -> content)
    // still matches perfectly - no DTO changes needed, just a different backend.
    private static final String GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";

    @Value("${groq.api.key}")
    private String apiKey;

    @Value("${groq.model}")
    private String model;

    // a class used to consume services/data from external api
    private RestTemplate template = new RestTemplate();

    // Used to convert the AI's JSON string into our Java variables
    private ObjectMapper objectMapper = new ObjectMapper();

    public String test() {
        return "AI Service is good";
    }

    public ClinicalReportResponse getClinicalData(List<String> chatHistory) {

        // 1. Set up the request headers, including the Groq API key
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(apiKey);

        // 2. Instruct the model to behave like the old Python service did:
        // read the conversation and hand back ONLY the three fields we persist.
        String systemPrompt = "You are a clinical data extraction assistant. Read the patient's chat "
                + "conversation and respond with ONLY a JSON object (no markdown fences, no extra text) "
                + "with exactly these keys: \"objectiveSummary\" (a short clinical-style summary string), "
                + "\"clinicalData\" (a JSON-encoded string of symptoms/vitals mentioned, or \"{}\" if none), "
                + "and \"biometricData\" (a JSON-encoded string of wearable/sensor data mentioned, or \"{}\" if none).";

        String conversation = String.join("\n", chatHistory);

        List<Map<String, String>> messages = new ArrayList<>();

        Map<String, String> systemMsg = new HashMap<>();
        systemMsg.put("role", "system");
        systemMsg.put("content", systemPrompt);
        messages.add(systemMsg);

        Map<String, String> userMsg = new HashMap<>();
        userMsg.put("role", "user");
        userMsg.put("content", conversation);
        messages.add(userMsg);

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("model", model);
        requestBody.put("messages", messages);

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        // 3. Create our clean internal response object up front, so we always return something
        ClinicalReportResponse clinicalReport = new ClinicalReportResponse();

        try {
            // 4. Call Groq, get JSON, convert into java object via AiRootResponse
            AiRootResponse response = template.postForObject(GROQ_URL, request, AiRootResponse.class);

            // 5. Fetch the raw text generated by the model from the nested JSON structure
            String rawAiJsonString = response.getChoices().get(0).getMessage().getContent();

            // 6. The model returned a JSON string. We read that string and map it to our object
            ClinicalReportResponse parsedData = objectMapper.readValue(rawAiJsonString, ClinicalReportResponse.class);

            clinicalReport.setObjectiveSummary(parsedData.getObjectiveSummary());
            clinicalReport.setClinicalData(parsedData.getClinicalData());
            clinicalReport.setBiometricData(parsedData.getBiometricData());

        } catch (Exception e) {
            // If Groq is unreachable or returns something unparsable, never let the request crash -
            // fall back to a safe placeholder, same defensive pattern as before.
            System.out.println("Error calling/parsing Groq response: " + e.getMessage());
            clinicalReport.setObjectiveSummary("AI DIAGNOSTIC OFFLINE: Unable to reach Groq. Manual doctor review required.");
            clinicalReport.setClinicalData("{}");
            clinicalReport.setBiometricData("{}");
        }

        // now everything fetched from Groq is set to clinicalReport object
        return clinicalReport;
    }
}
